### PR TITLE
Create RFC-00014: Atlaspad Launchpad

### PR DESCRIPTION
**Pull request by berkcicekk**

### CODE REVIEW

**Comment by chad11111** [comment]
@berkcicekk Thank you for the contribution - I will review this internally.

**Comment by chad11111** [comment]
@berkcicekk Can you please submit the RFC in english if possible ? Thank you

**Comment by berkcicekk** [comment]
> @berkcicekk Can you please submit the RFC in english if possible ? Thank you

Sorry, we neglected to add the English file. I'm updating it immediately.

**Comment by chad11111** [comment]
English version can be found here:

https://github.com/MinaFoundation/Core-Grants/pull/38

**Pull request closed without merging**
